package repo

var genreMap = map[string]string{
	"sf_history":             "Историческая фантастика",
	"sf_action":              "Боевая фантастика",
	"sf_detective":           "Детективная фантастика",
	"sf_cyberpunk":           "Киберпанк",
	"sf_space":               "Космическая фантастика",
	"sf_social":              "Социально-психологическая фантастика",
	"sf_horror":              "Ужасы и Мистика",
	"sf_humor":               "Юмористическая фантастика",
	"sf_fantasy":             "Фэнтези",
	"sf_epic":                "Эпическая фэнтези",
	"sf_heroic":              "Героическая фэнтези",
	"sf_detective_f":         "Детективная фэнтези",
	"sf_cyberpunk_f":         "Киберпанк фэнтези",
	"sf_space_f":             "Космическая фэнтези",
	"sf_social_f":            "Социально-психологическая фэнтези",
	"sf_horror_f":            "Ужасы и Мистика фэнтези",
	"sf_humor_f":             "Юмористическая фэнтези",
	"sf_fantasy_f":           "Фэнтези",
	"sf":                     "Научная фантастика",
	"sf_etc":                 "Фантастика: прочее",
	"sf_fantasy_city":        "Городское фэнтези",
	"sf_fantasy_irony":       "Ироническая фэнтези",
	"sf_irony":               "Ироническая фантастика",
	"sf_mystic":              "Мистика",
	"sf_postapocalyptic":     "Постапокалипсис",
	"sf_space_opera":         "Космическая опера",
	"det_classic":            "Классический детектив",
	"det_police":             "Полицейский детектив",
	"det_action":             "Боевик",
	"det_ironic":             "Иронический детектив",
	"det_history":            "Исторический детектив",
	"det_espionage":          "Шпионский детектив",
	"det_crime":              "Криминальный детектив",
	"det_political":          "Политический детектив",
	"det_maniac":             "Детектив про маньяков",
	"det_hard":               "Крутой детектив",
	"det_soft":               "Мягкий детектив",
	"det_thriller":           "Триллер",
	"det_legal":              "Юридический детектив",
	"det_cozy":               "Дамский детектив",
	"det_irony":              "Иронический детектив",
	"detective":              "Детективы",
	"prose_classic":          "Классическая проза",
	"prose_history":          "Историческая проза",
	"prose_contemporary":     "Современная проза",
	"prose_counter":          "Контркультура",
	"prose_rus_classic":      "Русская классика",
	"prose_su_classics":      "Советская классика",
	"prose_military":         "Военная проза",
	"prose_sentimental":      "Сентиментальная проза",
	"prose_magic":            "Магический реализм",
	"prose":                  "Проза",
	"love_contemporary":      "Современные любовные романы",
	"love_historical":        "Исторические любовные романы",
	"love_detective":         "Любовно-детективные романы",
	"love_short":             "Короткие любовные романы",
	"love_erotica":           "Эротика",
	"love":                   "Любовные романы",
	"love_hard":              "Остросюжетные любовные романы",
	"love_history":           "Исторические любовные романы",
	"love_sf":                "Любовная фантастика",
	"adv_western":            "Вестерн",
	"adv_history":            "Исторические приключения",
	"adv_detective":          "Приключенческий детектив",
	"adv_modern":             "Современные приключения",
	"adv_animal":             "Приключения про животных",
	"adv_maritime":           "Морские приключения",
	"adv_geo":                "Путешествия и География",
	"adv_all":                "Приключения",
	"adv_indian":             "Приключения про индейцев",
	"adventure":              "Приключения",
	"child_tale":             "Сказка",
	"child_verse":            "Детские стихи",
	"child_prose":            "Детская проза",
	"child_sf":               "Детская фантастика",
	"child_det":              "Детские детективы",
	"child_adv":              "Детские приключения",
	"child_education":        "Детская образовательная литература",
	"children":               "Детская литература",
	"poetry":                 "Поэзия",
	"humor_prose":            "Юмористическая проза",
	"humor_verse":            "Юмористические стихи",
	"humor":                  "Юмор",
	"humor_anecdote":         "Анекдоты",
	"humor_fantasy":          "Юмористическая фантастика",
	"humor_satire":           "Сатира",
	"sci_history":            "История",
	"sci_psychology":         "Психология",
	"sci_culture":            "Культурология",
	"sci_religion":           "Религия",
	"sci_philosophy":         "Философия",
	"sci_politics":           "Политика",
	"sci_business":           "Бизнес",
	"sci_juris":              "Юриспруденция",
	"sci_linguistic":         "Лингвистика",
	"sci_medicine":           "Медицина",
	"sci_phys":               "Физика",
	"sci_math":               "Математика",
	"sci_chem":               "Химия",
	"sci_biology":            "Биология",
	"sci_tech":               "Технические науки",
	"sci_cosmos":             "Космос",
	"sci_economy":            "Экономика",
	"sci_geo":                "География",
	"sci_pedagogy":           "Педагогика",
	"sci_philology":          "Филология",
	"sci_popular":            "Занимательная наука",
	"sci_radio":              "Радио",
	"sci_social_studies":     "Обществознание",
	"sci_state":              "Государство и право",
	"sci_textbook":           "Учебник",
	"sci_transport":          "Транспорт",
	"sci_veterinary":         "Ветеринария",
	"sci_zoo":                "Зоология",
	"science":                "Наука",
	"comp_www":               "Интернет",
	"comp_programming":       "Программирование",
	"comp_soft":              "Программное обеспечение",
	"comp_db":                "Базы данных",
	"comp_os":                "Операционные системы",
	"computers":              "Компьютеры",
	"ref_encyc":              "Энциклопедия",
	"ref_dict":               "Словарь",
	"ref_ref":                "Справочник",
	"ref_guide":              "Путеводитель",
	"reference":              "Справочная литература",
	"nonf_biography":         "Биографии и Мемуары",
	"nonf_publicism":         "Пупублицистика",
	"nonf_criticism":         "Критика",
	"nonf_military":          "Военная документалистика",
	"nonfiction":             "Документальная литература",
	"design":                 "Искусство и Дизайн",
	"religion_rel":           "Религия",
	"religion_esoterics":     "Эзотерика",
	"religion_self":          "Самосовершенствование",
	"religion_budda":         "Буддизм",
	"religion_catholicism":   "Католицизм",
	"religion_christianity":  "Христианство",
	"religion_hinduism":      "Индуизм",
	"religion_islam":         "Ислам",
	"religion_judaism":       "Иудаизм",
	"religion_orthodoxy":     "Православие",
	"religion_paganism":      "Язычество",
	"religion_protestantism": "Протестантизм",
	"religion":               "Религия",
	"home_cooking":           "Кулинария",
	"home_pets":              "Домашние животные",
	"home_crafts":            "Хобби и Ремесла",
	"home_garden":            "Сад и Огород",
	"home_diy":               "Сделай сам",
	"home_sport":             "Спорт",
	"home_health":            "Здоровье",
	"home_entertain":         "Развлечения",
	"home_sex":               "Секс",
	"home":                   "Дом и Семья",
	"antique":                "Античная литература",
	"antique_ant":            "Античная драматургия",
	"antique_east":           "Древневосточная литература",
	"antique_european":       "Древнеевропейская литература",
	"antique_myths":          "Мифы. Легенды. Эпос",
	"antique_russian":        "Древнерусская литература",
	"aphorisms":              "Афоризмы",
	"art_criticism":          "Искусствоведение",
	"astrology":              "Астрология",
	"auto_business":          "Автодело",
	"auto_regulations":       "ПДД",
	"banking":                "Банковское дело",
	"cine":                   "Кино",
	"comedy":                 "Комедия",
	"dramaturgy":             "Драматургия",
	"economics":              "Экономика",
	"epic_poetry":            "Эпическая поэзия",
	"epistolary_fiction":     "Эпистолярная проза",
	"experimental_poetry":    "Экспериментальная поэзия",
	"fable":                  "Басня",
	"fairy_fantasy":          "Мифологическое фэнтези",
	"fanfiction":             "Фанфик",
	"folk_songs":             "Народные песни",
	"folk_tale":              "Народная сказка",
	"folklore":               "Фольклор",
	"foreign_language":       "Иностранные языки",
	"geo_guides":             "Путеводители",
	"great_story":            "Повесть",
	"historical_fantasy":     "Историческое фэнтези",
	"in_verse":               "В стихах",
	"literature_18":          "Литература XVIII века",
	"literature_19":          "Литература XIX века",
	"literature_20":          "Литература XX века",
	"lyrics":                 "Лирика",
	"management":             "Менеджмент",
	"marketing":              "Маркетинг",
	"military_all":           "Военное дело",
	"military_arts":          "Боевые искусства",
	"military_history":       "Военная история",
	"military_special":       "Спецслужбы",
	"military_weapon":        "Оружие",
	"music":                  "Музыка",
	"network_literature":     "Сетевая литература",
	"periodic":               "Периодика",
	"personal_finance":       "Личные финансы",
	"popadanec":              "Попаданцы",
	"popular_business":       "Популярный бизнес",
	"proverbs":               "Пословицы, поговорки",
	"psy_sex_and_family":     "Секс и семейная психология",
	"psy_theraphy":           "Психотерапия",
	"scenarios":              "Сценарии",
	"short_story":            "Рассказ",
	"song_poetry":            "Песенная поэзия",
	"stock":                  "Ценные бумаги",
	"story":                  "Повесть",
	"theatre":                "Театр",
	"thriller":               "Триллер",
	"thriller_medical":       "Медицинский триллер",
	"thriller_techno":        "Технотриллер",
	"tragedy":                "Трагедия",
	"unfinished":             "Недописанное",
	"vaudeville":             "Водевиль",
	"visual_arts":            "Визуальные искусства",
	"ya":                     "Подростковая литература",
	"essay":                  "Эссе",
	"drama":                  "Драма",
	"roman":                  "Роман",
	"sagas":                  "Саги",
}

// MapGenre translates FB2 genre tag to human-readable name
func MapGenre(tag string) string {
	if name, ok := genreMap[tag]; ok {
		return name
	}
	return tag
}
